### ISSUE TITLE
cannot import data

### ISSUE THREAD

**Issue by wushupei1997** [shchur/gnn-benchmark#9]
Traceback (most recent call last):
  File "/home/w/Projects/gnn-benchmark/gnnbench/run_single_job.py", line 12, in <module>
    import gnnbench.models
  File "/home/w/anaconda3/envs/tf1.9/lib/python3.6/site-packages/gnnbench-0.1.0-py3.6.egg/gnnbench/__init__.py", line 1, in <module>
    from . import data
ImportError: cannot import name 'data'

How can I solve this problem?

**Comment by shchur** [comment]
It seems that the package wasn't installed correctly, please have a look at the [installation instructions](https://github.com/shchur/gnn-benchmark#installation).
